### ISSUE TITLE
Not working on OSX

### ISSUE THREAD

**Issue by Pasenchuk** [GripQA/commit-entropy#1] opened 2015-07-10 19:17 UTC
bash-3.2# commit-entropy csv
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/commit_entropy/commands/csv_printer.py", line 6, in <module>
    from entropy.parser.git_log_parser import GitLogParser
ImportError: No module named 'entropy'

After (may be irrelevant action):
bash-3.2# pip3 install entropy
bash-3.2# commit-entropy csv
ImportError: No module named 'entropy.parser'; 'entropy' is not a package

**Comment by kmile** [comment] 2015-07-10 20:41
Should be fixed in v0.1.1. Can you try `pip3 install commit-entropy` again?

**Comment by Pasenchuk** [comment] 2015-07-12 00:22
Tried, no effect.

**Comment by kmile** [comment] 2015-07-13 10:17
My bad, forgot the `-U`. Try

```
pip3 install -U commit-entropy
```

to update the package to the latest version. If that doesn't work, try uninstalling and reinstalling the package:

```
pip3 uninstall commit-entropy
pip3 install commit-entropy
```

Check it is version 0.1.1 by running

```
pip3 show commit-entropy
```

Paste the output of that last command in here if it still fails.

**Comment by Pasenchuk** [comment] 2015-07-13 12:44
Ok, now it works. Thanks.
But I have date in format like "20140305" without delimiters.

**Comment by kmile** [comment] 2015-07-13 13:11
Great to hear it worked!

The date format is by design. It's the ISO 8601 'basic' format for a date. I'll close this one, feel free to open up another issue to pick the date format if you need any other format ;)

**Closed as completed by kmile** 2015-07-13 13:11 UTC
Labels: bug
